### ISSUE TITLE
Review and update

### ISSUE THREAD

**Issue by b286** [openUC2/UC2-Ptycho#1]
Please check that the information provided here is correct and if possible update the repository. Thank you ❤️

Also: if this branch grow further under someone else's maintenance, please point the to this repository.

**Comment by beniroquai** [comment]
Thanks! I think it's alright for now since it has not been published yet. We will update it together with PtyLab once this is published too!

**Comment by beniroquai** [comment]
So far it looks great! Thanks for transferring it here!
